import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { PiSquaresFour } from "react-icons/pi";
import { IoDocumentTextOutline } from "react-icons/io5";
import { CgProfile } from "react-icons/cg";
import styles from "./layout.module.css";
import { FaCheckCircle } from "react-icons/fa";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Sidebar */}

        <div className="flex ">
          <div className="p-8 bg-gray-100 md:w-1/5 sm:w-full">
            <div className="h-80">
              <div className="flex items-center	gap-2 my-6 text-green-900 text-lg font-semibold">
                <FaCheckCircle className="text-green-500" />
                quicktest
              </div>
              <div className="flex items-center	gap-2 my-6">
                <PiSquaresFour className="w-5 h-5" />
                Home
              </div>
              <h5 className="flex items-center	gap-2 my-6">
                <IoDocumentTextOutline className="w-5 h-5" />
                Tests
              </h5>
              <h5 className="flex items-center	gap-2 my-6">
                <CgProfile className="w-5 h-5" />
                Profile
              </h5>
            </div>

            <hr className="h-px my-8 bg-gray-400 border-0 dark:bg-gray-700"></hr>

            <div>
              <p className="text-sm/[2px] my-7">ACTIVE TESTS</p>
              <h5 className="my-7 font-semibold">General Aptitude</h5>
              <h5 className="my-7">Basic Math</h5>
              <h5 className="my-7">Logical Reasoning</h5>
              <h5 className="my-7">Microsoft Excel</h5>
            </div>



          </div>

          <div className="p-8 md:w-full sm:w-0">{children}</div>
        </div>
      </body>
    </html>
  );
}
